openapi: 3.1.0
info:
  title: Zapier Webhook Proxy
  description: Sends arbitrary JSON data to your Zapier Catch Hook URL.
  version: 1.0.0
servers:
  - url: https://hooks.zapier.com
    description: Zapier Webhooks base URL
paths:
  /hooks/catch/20905516/ub2oq7t/:
    post:
      operationId: sendToZapier
      summary: Send data to Zapier Webhook
      description: Posts a JSON payload to your Zapier webhook to trigger automations.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              description: Any custom data to send to Zapier
              additionalProperties: true
      responses:
        '200':
          description: Successfully sent to Zapier
          content:
            application/json:
              schema:
                type: object
                additional
