openapi: 3.0.0
info:
title: Zapier Webhook Action
version: "1.0.0"
description: Send task data from GPT to Zapier via webhook
servers:
- url: https://hooks.zapier.com/hooks/catch/20905516/ub2oq7t/
paths:
/:
post:
summary: Send task to Zapier
operationId: sendToZapier
requestBody:
required: true
content:
application/json:
schema:
type: object
properties:
task:
type: string
description: The task to be sent to Zapier
required:
- task
responses:
'200':
description: Success
